In [1]:
import torch
import numpy

In [2]:
x = torch.tensor([1.5, 2])
print(x)
print(x.device)

tensor([1.5000, 2.0000])
cpu


In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda:0")
else:
    device = torch.device("cpu")

In [5]:
device

device(type='cpu')

In [11]:
 t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [16]:
t = t.reshape([1,12])

In [19]:
t.squeeze_()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [20]:
t.shape


torch.Size([12])

In [21]:
t.unsqueeze(dim=0)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [22]:
t.shape

torch.Size([12])

In [23]:
t.unsqueeze(dim=1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [24]:
t.shape

torch.Size([12])

In [6]:
from torchvision import datasets

In [7]:
path2data = "./data"

train_data = datasets.MNIST(path2data, train=True, download=True)

Processing...
Done!


In [9]:
x_train, y_train = train_data.train_data, train_data.train_labels

In [10]:
val_data = datasets.MNIST(path2data, train=False, download=True)

In [27]:
x_val, y_val = val_data.test_data, val_data.test_labels

In [26]:
# add a dimension to tensor to become B*C*H*W
if len(x_train.shape) == 3:
    x_train = x_train.unsqueeze(dim=1)
print(x_train.shape)

torch.Size([60000, 1, 28, 28])


In [30]:
if len(x_val.shape) == 3:
    x_val = x_val.unsqueeze(dim=1)
print(x_val.shape)

torch.Size([10000, 1, 28, 28])


In [31]:
from torch.utils.data import TensorDataset

train_ds = TensorDataset(x_train, y_train)

In [32]:
from torch.utils.data import DataLoader
train_dl = DataLoader(train_ds, batch_size=8)

In [33]:
from torch import nn

In [34]:
model = nn.Sequential(
    nn.Linear(4, 5),
    nn.ReLU(),
    nn.Linear(5,1),

)

In [35]:
print(model)

Sequential(
  (0): Linear(in_features=4, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)
