In [1]:
import torch

In [11]:
t = torch.Tensor([[1,2,3],[4,5,6]])

In [12]:
t.requires_grad

False

In [13]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
t.requires_grad_()  #this is will make requires_grad = True

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [17]:
t2 = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, requires_grad=True)

In [18]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [21]:
with torch.no_grad():
    new_tensor = t*3
    print(new_tensor)

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])


In [25]:
t_nograd = torch.tensor([1,3,5,7], dtype=torch.float32, requires_grad = True)

In [26]:
with torch.enable_grad():
    new_torch_grad = t_nograd * 3
    print(new_torch_grad)

tensor([ 3.,  9., 15., 21.], grad_fn=<MulBackward0>)


In [27]:
with torch.no_grad():
    t_no = t_nograd * 2
    print(t_no)

tensor([ 2.,  6., 10., 14.])


In [29]:
detached_tensor = t2.detach()

In [31]:
detached_tensor # by default detach() will have required_grad= False

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
mean_tensor = (t2 + detached_tensor).mean()

In [33]:
mean_tensor

tensor(7., grad_fn=<MeanBackward0>)

In [34]:
mean_tensor.backward()

In [35]:
t2.grad

tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])

In [41]:
detached_tensor.grad == None

True

In [42]:
from torch.autograd import Variable

In [43]:
var = Variable(torch.FloatTensor([9, 2, 3]))

In [46]:
var.requires_grad = True

In [50]:
# No need to use Variable anymore. Now PyTorch torch.tensor is capable of doing everything that a Variable does